#ifndef ZEROPOINT_CHARACTER_RACE_H
#define ZEROPOINT_CHARACTER_RACE_H

struct str_app_type
{
   short tohit;
   short todam;
   short carry;
   short wield;
};

struct int_app_type
{
   short learn;
};

struct wis_app_type
{
   short practice;
};

struct dex_app_type
{
   short defensive;
};

struct con_app_type
{
   short hitp;
   short shock;
};

struct cha_app_type
{
   short charm;
};

struct lck_app_type
{
   short luck;
};

struct frc_app_type
{
   short force;
};

/* ability classes */

#define ABILITY_NONE		-1
#define COMBAT_ABILITY 		0
#define PILOTING_ABILITY	1
#define ENGINEERING_ABILITY	2
#define HUNTING_ABILITY		3
#define SMUGGLING_ABILITY	4
#define DIPLOMACY_ABILITY	5
#define LEADERSHIP_ABILITY	6
#define FORCE_ABILITY		7

#define MAX_CHARACTER_TRAITS 6

typedef enum
{
   TRAIT_NONE = 0,
   TRAIT_POWERFUL_BUILD,
   TRAIT_WEAK_BUILD,
   TRAIT_ROBUST_PHYSIOLOGY,
   TRAIT_FRAIL_PHYSIOLOGY,
   TRAIT_QUICK_REFLEXES,
   TRAIT_SLUGGISH_REFLEXES,
   TRAIT_ANALYTICAL_MIND,
   TRAIT_SLOW_MIND,
   TRAIT_DISCIPLINED_MIND,
   TRAIT_WEAK_WILLED,
   TRAIT_COMMANDING_PRESENCE,
   TRAIT_SOCIALLY_AWKWARD,
   TRAIT_FORTUNATE,
   TRAIT_ILL_FATED,
   TRAIT_FORCE_ATTUNED,
   TRAIT_FORCE_DULL,
   TRAIT_TOXIN_RESISTANT,
   TRAIT_TOXIN_SENSITIVE,
   TRAIT_STEADY_NERVOUS_SYSTEM,
   TRAIT_PARALYSIS_PRONE,
   TRAIT_STRONG_LUNGS,
   TRAIT_WEAK_LUNGS,
   TRAIT_DEVICE_HARDENED,
   TRAIT_DEVICE_SUSCEPTIBLE,
   TRAIT_FORCE_RESISTANT,
   TRAIT_FORCE_SUSCEPTIBLE,
   TRAIT_NATURAL_MARKSMAN,
   TRAIT_POOR_SHOT,
   TRAIT_BOWCASTER_SAVANT,
   TRAIT_BOWCASTER_INEPT,
   TRAIT_PIKE_FIGHTER,
   TRAIT_PIKE_CLUMSY,
   TRAIT_SABER_INSTINCT,
   TRAIT_SABER_HESITATION,
   TRAIT_VIBROBLADE_HAND,
   TRAIT_POOR_BLADE_CONTROL,
   TRAIT_SHIELD_DISCIPLINE,
   TRAIT_POOR_SHIELD_DISCIPLINE,
   TRAIT_EVASIVE_INSTINCT,
   TRAIT_FLAT_FOOTED,
   TRAIT_DEFENSIVE_GUARD,
   TRAIT_OPEN_GUARD,
   TRAIT_DISARMING_HAND,
   TRAIT_WEAK_WEAPON_CONTROL,
   TRAIT_AMBIDEXTROUS,
   TRAIT_OFFHAND_INEPT,
   TRAIT_HEAVY_HITTER,
   TRAIT_WEAK_STRIKER,
   TRAIT_SNIPERS_PATIENCE,
   TRAIT_IMPATIENT_SHOOTER,
   TRAIT_THROWING_ARM,
   TRAIT_POOR_THROWER,
   TRAIT_GRENADIER,
   TRAIT_EXPLOSIVES_NERVOUSNESS,
   TRAIT_FIELD_MEDIC,
   TRAIT_SQUEAMISH,
   TRAIT_NATURAL_TRACKER,
   TRAIT_POOR_TRACKER,
   TRAIT_KEEN_SEARCHER,
   TRAIT_INATTENTIVE,
   TRAIT_QUIET_STEP,
   TRAIT_HEAVY_FOOTED,
   TRAIT_CONCEALMENT_INSTINCT,
   TRAIT_CONSPICUOUS,
   TRAIT_LOCK_SENSE,
   TRAIT_CLUMSY_LOCKSMITH,
   TRAIT_SHIPLOCK_SPECIALIST,
   TRAIT_SHIPLOCK_INEPT,
   TRAIT_HIJACKERS_NERVE,
   TRAIT_BOARDING_HESITATION,
   TRAIT_SLICERS_MIND,
   TRAIT_TECHNOLOGICALLY_INEPT,
   TRAIT_FIGHTER_PILOT,
   TRAIT_FIGHTER_ANXIETY,
   TRAIT_FREIGHTER_HAND,
   TRAIT_POOR_MIDSHIP_HANDLING,
   TRAIT_CAPITAL_COMMAND,
   TRAIT_CAPITALSHIP_OVERLOAD,
   TRAIT_ASTROGATION_INSTINCT,
   TRAIT_DIRECTIONALLY_CHALLENGED,
   TRAIT_GUNNERY_INSTINCT,
   TRAIT_POOR_GUNNER,
   TRAIT_SYSTEMS_APTITUDE,
   TRAIT_SYSTEMS_CONFUSION,
   TRAIT_TRACTOR_PRECISION,
   TRAIT_POOR_TRACTOR_CONTROL,
   TRAIT_SHIP_MECHANIC,
   TRAIT_MECHANICAL_INEPTITUDE,
   TRAIT_ARMOUR_SMITH,
   TRAIT_POOR_ARMOURER,
   TRAIT_BLASTER_SMITH,
   TRAIT_POOR_GUNSMITH,
   TRAIT_SHIELD_ENGINEER,
   TRAIT_POOR_SHIELD_ENGINEER,
   TRAIT_SABER_CRAFTSMAN,
   TRAIT_POOR_SABER_CRAFTSMAN,
   TRAIT_INTELLIGENCE_OPERATIVE,
   TRAIT_POOR_ANALYST,
   TRAIT_SMOOTH_TALKER,
   TRAIT_POOR_CONVERSATIONALIST,
   TRAIT_MAX
} trait_id;

typedef enum
{
   TRAIT_EFFECT_NONE,
   TRAIT_EFFECT_STR_POTENTIAL,
   TRAIT_EFFECT_CON_POTENTIAL,
   TRAIT_EFFECT_DEX_POTENTIAL,
   TRAIT_EFFECT_INT_POTENTIAL,
   TRAIT_EFFECT_WIS_POTENTIAL,
   TRAIT_EFFECT_CHA_POTENTIAL,
   TRAIT_EFFECT_LCK_POTENTIAL,
   TRAIT_EFFECT_FRC_POTENTIAL,
   TRAIT_EFFECT_SAVE_POISON,
   TRAIT_EFFECT_SAVE_PARA,
   TRAIT_EFFECT_SAVE_BREATH,
   TRAIT_EFFECT_SAVE_WAND,
   TRAIT_EFFECT_SAVE_FORCE,
   TRAIT_EFFECT_SKILL_BLASTERS,
   TRAIT_EFFECT_SKILL_BOWCASTERS,
   TRAIT_EFFECT_SKILL_FORCE_PIKES,
   TRAIT_EFFECT_SKILL_LIGHTSABERS,
   TRAIT_EFFECT_SKILL_VIBRO_BLADES,
   TRAIT_EFFECT_SKILL_SHIELDWORK,
   TRAIT_EFFECT_SKILL_DODGE,
   TRAIT_EFFECT_SKILL_PARRY,
   TRAIT_EFFECT_SKILL_DISARM,
   TRAIT_EFFECT_SKILL_DUAL_WIELD,
   TRAIT_EFFECT_SKILL_ENHANCED_DAMAGE,
   TRAIT_EFFECT_SKILL_SNIPE,
   TRAIT_EFFECT_SKILL_THROW,
   TRAIT_EFFECT_SKILL_GRENADES,
   TRAIT_EFFECT_SKILL_FIRST_AID,
   TRAIT_EFFECT_SKILL_TRACK,
   TRAIT_EFFECT_SKILL_SEARCH,
   TRAIT_EFFECT_SKILL_SNEAK,
   TRAIT_EFFECT_SKILL_HIDE,
   TRAIT_EFFECT_SKILL_PICK_LOCK,
   TRAIT_EFFECT_SKILL_PICKSHIPLOCK,
   TRAIT_EFFECT_SKILL_HIJACK,
   TRAIT_EFFECT_SKILL_SLICE,
   TRAIT_EFFECT_SKILL_STARFIGHTERS,
   TRAIT_EFFECT_SKILL_MIDSHIPS,
   TRAIT_EFFECT_SKILL_CAPITALSHIPS,
   TRAIT_EFFECT_SKILL_NAVIGATION,
   TRAIT_EFFECT_SKILL_WEAPONSYSTEMS,
   TRAIT_EFFECT_SKILL_SHIPSYSTEMS,
   TRAIT_EFFECT_SKILL_TRACTORBEAMS,
   TRAIT_EFFECT_SKILL_SHIPMAINTENANCE,
   TRAIT_EFFECT_SKILL_MAKEARMOR,
   TRAIT_EFFECT_SKILL_MAKEBLASTER,
   TRAIT_EFFECT_SKILL_MAKESHIELD,
   TRAIT_EFFECT_SKILL_LIGHTSABER_CRAFTING,
   TRAIT_EFFECT_SKILL_GATHER_INTELLIGENCE,
   TRAIT_EFFECT_SKILL_SMALLTALK,
   TRAIT_EFFECT_MAX
} trait_effect;

struct character_trait
{
   short id;
   short rank;
};

/* the races */
#define RACE_HUMAN	    0
#define RACE_WOOKIEE		1
#define RACE_TWI_LEK		2
#define RACE_RODIAN		3
#define RACE_HUTT		4
#define RACE_MON_CALAMARI	5
#define RACE_NOGHRI		6
#define RACE_GAMORREAN		7
#define RACE_JAWA		8
#define RACE_ADARIAN            9
#define RACE_EWOK              10
#define RACE_VERPINE           11
#define RACE_DEFEL             12
#define RACE_TRANDOSHAN        13
#define RACE_CHADRA_FAN        14
#define RACE_DUINUOGWUIN       16   /* big mistake was causing mass chaos */
#define RACE_QUARREN           15

/*
* Languages -- Altrag
*/
#define LANG_COMMON      BV00 /* Human base language */
#define LANG_WOOKIEE     BV01
#define LANG_TWI_LEK     BV02
#define LANG_RODIAN      BV03
#define LANG_HUTT        BV04
#define LANG_MON_CALAMARI   BV05
#define LANG_NOGHRI      BV06
#define LANG_EWOK        BV07
#define LANG_ITHORIAN    BV08
#define LANG_GOTAL       BV09
#define LANG_DEVARONIAN  BV10
#define LANG_DROID       BV11
#define LANG_SPIRITUAL   BV12
#define LANG_MAGICAL     BV13
#define LANG_GAMORREAN   BV14
#define LANG_GOD         BV15
#define LANG_ANCIENT     BV16
#define LANG_JAWA        BV17
#define LANG_CLAN	 BV18
#define LANG_ADARIAN	 BV19
#define LANG_VERPINE	 BV20
#define LANG_DEFEL       BV21
#define LANG_TRANDOSHAN  BV22
#define LANG_CHADRA_FAN  BV23
#define LANG_QUARREN     BV24
#define LANG_DUINUOGWUIN BV25
#define LANG_UNKNOWN        0 /* Anything that doesnt fit a category */
#define VALID_LANGS    ( LANG_COMMON | LANG_WOOKIEE | LANG_TWI_LEK | LANG_RODIAN  \
   | LANG_HUTT | LANG_MON_CALAMARI | LANG_NOGHRI | LANG_GAMORREAN \
   | LANG_JAWA | LANG_ADARIAN | LANG_EWOK | LANG_VERPINE | LANG_DEFEL \
   | LANG_TRANDOSHAN | LANG_CHADRA_FAN | LANG_QUARREN | LANG_DUINUOGWUIN)
/*  26 Languages */

#endif /* ZEROPOINT_CHARACTER_RACE_H */
